name: find_recipes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  auto_size_text: ^2.1.0
  flutter_launcher_icons: ^0.7.5
  flutter_mobx: ^1.1.0
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  mobx: ^1.2.1
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

flutter_icons:
  image_path: "assets/launcher_icons/icon.png"
  android: true
  ios: true
  # adaptive_icon_background: "assets/launcher_icons/background.png"
  # adaptive_icon_foreground: "assets/launcher_icons/foreground.png"
